# Configuration for root across all crates


[build]
# Specify when building to build for x86_64-unknown-none architecture
target = "x86_64-unknown-none"

[unstable]
# Enables unstable features
bindeps = true